### ISSUE TITLE
Game crash when trading in inventory

### ISSUE THREAD

**Issue by drpolarnimedo** [iamshift/PickableVillagers#13]
[05/07/2023 17:58:00 PM] Launching pack 1.20.1 1.20.1 (ATLauncher) for Minecraft 1.20.1
[05/07/2023 17:58:00 PM] Logging into Minecraft!
[05/07/2023 17:58:00 PM] Using Java runtime java-runtime-gamma (Java 17.0.3) at path **USERSDIR**\runtimes\minecraft\java-runtime-gamma\windows-x64\java-runtime-gamma
[05/07/2023 17:58:00 PM] Loader: Fabric 0.14.21
[05/07/2023 17:58:00 PM] Mods:
[05/07/2023 17:58:00 PM]  - \cloth-config-11.0.99-fabric.jar
[05/07/2023 17:58:00 PM]  - \collective-1.20.1-6.62.jar
[05/07/2023 17:58:00 PM]  - \cristellib-fabric-1.1.jar
[05/07/2023 17:58:00 PM]  - \fabric-api-0.85.0+1.20.1.jar (Added)
[05/07/2023 17:58:00 PM]  - \fabric-language-kotlin-1.9.6+kotlin.1.8.22.jar
[05/07/2023 17:58:00 PM]  - \geckolib-fabric-1.20-4.2.jar
[05/07/2023 17:58:00 PM]  - \libIPN-fabric-1.20-3.0.2.jar
[05/07/2023 17:58:00 PM]  - \lithium-fabric-mc1.20.1-0.11.2.jar
[05/07/2023 17:58:00 PM]  - \malilib-fabric-1.20.1-0.16.1.jar
[05/07/2023 17:58:00 PM]  - \midnightlib-fabric-1.4.1.jar
[05/07/2023 17:58:00 PM]  - \modmenu-7.1.0.jar (Added)
[05/07/2023 17:58:00 PM]  - \pickable_villagers-1.4.1+1.20.1.jar (Added)
[05/07/2023 17:58:00 PM]  - \resourcefulconfig-fabric-1.20-2.0.0.jar
[05/07/2023 17:58:00 PM]  - \trade-cycling-fabric-1.20.1-1.0.5.jar

...

[05/07/2023 17:59:03 PM] 	at com.iamshift.pickablevillagers.entities.FakeMerchant.method_18008(FakeMerchant.java:53)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_3988.method_8262(class_3988.java:133)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1727.method_7667(class_1727.java:59)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1728.method_7601(class_1728.java:147)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1703.method_30010(class_1703.java:394)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1703.method_7593(class_1703.java:294)
[05/07/2023 17:59:03 PM] 	at com.iamshift.pickablevillagers.screen.TradeScreenHandler.method_7593(TradeScreenHandler.java:47)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_3244.method_12076(class_3244.java:1682)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_2813.method_12191(class_2813.java:58)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_2813.method_11054(class_2813.java:13)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_2600.method_11072(class_2600.java:22)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_3738.run(class_3738.java:18)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1255.method_18859(class_1255.java:156)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1255.method_16075(class_1255.java:130)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1255.method_18857(class_1255.java:139)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[05/07/2023 17:59:03 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[05/07/2023 17:59:03 PM] [Server thread/ERROR] Encountered an unexpected exception
[05/07/2023 17:59:03 PM] [Server thread/ERROR] This crash report has been saved to: **USERSDIR**\instances\test2\crash-reports\crash-2023-07-05_17.59.03-server.txt
[05/07/2023 17:59:03 PM] [Server thread/INFO] Stopping server
[05/07/2023 17:59:03 PM] [Server thread/INFO] Saving players
[05/07/2023 17:59:03 PM] ---- Minecraft Crash Report ----
[05/07/2023 17:59:03 PM] // Uh... Did I do that?
[05/07/2023 17:59:03 PM] 
[05/07/2023 17:59:03 PM] Time: 2023-07-05 17:59:03
[05/07/2023 17:59:03 PM] Description: Exception in server tick loop
[05/07/2023 17:59:03 PM] 
[05/07/2023 17:59:03 PM] java.lang.IllegalAccessError: class com.iamshift.pickablevillagers.entities.FakeMerchant tried to access private field net.minecraft.class_1646.field_18530 (com.iamshift.pickablevillagers.entities.FakeMerchant and net.minecraft.class_1646 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @62e136d3)
[05/07/2023 17:59:03 PM] 	at com.iamshift.pickablevillagers.entities.FakeMerchant.method_18008(FakeMerchant.java:53)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_3988.method_8262(class_3988.java:133)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1727.method_7667(class_1727.java:59)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1728.method_7601(class_1728.java:147)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1703.method_30010(class_1703.java:394)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1703.method_7593(class_1703.java:294)
[05/07/2023 17:59:03 PM] 	at com.iamshift.pickablevillagers.screen.TradeScreenHandler.method_7593(TradeScreenHandler.java:47)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_3244.method_12076(class_3244.java:1682)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_2813.method_12191(class_2813.java:58)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_2813.method_11054(class_2813.java:13)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_2600.method_11072(class_2600.java:22)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_3738.run(class_3738.java:18)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1255.method_18859(class_1255.java:156)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1255.method_16075(class_1255.java:130)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
[05/07/2023 17:59:03 PM] 	at net.minecraft.class_1255.method_18857(class_1255.java:139)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
[05/07/2023 17:59:03 PM] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[05/07/2023 17:59:03 PM] 	at java.base/java.lang.Thread.run(Thread.java:833)
[05/07/2023 17:59:03 PM] 
[05/07/2023 17:59:03 PM] 
[05/07/2023 17:59:03 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[05/07/2023 17:59:03 PM] ---------------------------------------------------------------------------------------
[05/07/2023 17:59:03 PM] 
[05/07/2023 17:59:03 PM] -- System Details --
[05/07/2023 17:59:03 PM] Details:
[05/07/2023 17:59:03 PM] 	Minecraft Version: 1.20.1
[05/07/2023 17:59:03 PM] 	Minecraft Version ID: 1.20.1
[05/07/2023 17:59:03 PM] 	Operating System: Windows 11 (amd64) version 10.0
[05/07/2023 17:59:03 PM] 	Java Version: 17.0.3, Microsoft
[05/07/2023 17:59:03 PM] 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft

...

[05/07/2023 17:59:03 PM] 	Fabric Mods: 
[05/07/2023 17:59:03 PM] 		cloth-config: Cloth Config v11 11.0.99
[05/07/2023 17:59:03 PM] 			cloth-basic-math: cloth-basic-math 0.6.1
[05/07/2023 17:59:03 PM] 		collective: Collective 6.62
[05/07/2023 17:59:03 PM] 		cristellib: Cristel Lib 1.1
[05/07/2023 17:59:03 PM] 			blue_endless_jankson: jankson 1.2.1
[05/07/2023 17:59:03 PM] 		fabric-api: Fabric API 0.85.0+1.20.1
[05/07/2023 17:59:03 PM] 			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
[05/07/2023 17:59:03 PM] 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
[05/07/2023 17:59:03 PM] 			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
[05/07/2023 17:59:03 PM] 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+97bb207577
[05/07/2023 17:59:03 PM] 			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
[05/07/2023 17:59:03 PM] 			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
[05/07/2023 17:59:03 PM] 			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
[05/07/2023 17:59:03 PM] 			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.8+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
[05/07/2023 17:59:03 PM] 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.12+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
[05/07/2023 17:59:03 PM] 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
[05/07/2023 17:59:03 PM] 			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.8+40e50c4677
[05/07/2023 17:59:03 PM] 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
[05/07/2023 17:59:03 PM] 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
[05/07/2023 17:59:03 PM] 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.38+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.42+9e7660c677
[05/07/2023 17:59:03 PM] 			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.48+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
[05/07/2023 17:59:03 PM] 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.0+6beca84877
[05/07/2023 17:59:03 PM] 			fabric-particles-v1: Fabric Particles (v1) 1.1.0+201a23a077
[05/07/2023 17:59:03 PM] 			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
[05/07/2023 17:59:03 PM] 			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
[05/07/2023 17:59:03 PM] 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
[05/07/2023 17:59:03 PM] 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
[05/07/2023 17:59:03 PM] 			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
[05/07/2023 17:59:03 PM] 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.8+e3d6ed2577
[05/07/2023 17:59:03 PM] 			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
[05/07/2023 17:59:03 PM] 			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.3+43a3fedd77
[05/07/2023 17:59:03 PM] 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
[05/07/2023 17:59:03 PM] 		fabric-language-kotlin: Fabric Language Kotlin 1.9.6+kotlin.1.8.22
[05/07/2023 17:59:03 PM] 			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
[05/07/2023 17:59:05 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[05/07/2023 17:59:05 PM] Checking for updated files!
[05/07/2023 17:59:09 PM] Copied Log to clipboard

**Comment by shiftthedev** [comment]
fixed in version 1.4.2
